codecov:
  token: e6016f31-4645-432d-85b8-e094a55ad832
  branch: dev
  require_ci_to_pass: yes
  # strict_yaml_branch: dev  # only use the latest copy on master branch
  # max_report_age: off # Codecov will reject reports that are over 12 hours old according to the timestamp in the report

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
